### ISSUE TITLE
Causes laggy / stuttery mouse cursor

### ISSUE THREAD

**Issue by Ririshi** [mgth/LittleBigMouse#163]
When LBM is running, I can "feel" the cursor stuttering or dragging behind a little bit, every few seconds. I am using a triple Dell monitor setup. When LBM and its daemon are both stopped, there is no stuttering at all. When the daemon is running (and the tray icon is visible), the stuttering is noticeable.

I think it may have something to do with the DCC/CI (e.g. remote configuration of monitor contrast, brightness and colours). A few months ago, I used the Dell Display Manager (DDM) tool to configure my displays. This tool also caused cursor stuttering. It also caused visible frame rate drops in games, which were backed up by a drop in GPU usage. Shutting down DDM completely resolved the issue, and this is also the case with LBM.

I'm afraid I cannot provide any more detail than this right now. Maybe there are logs or other diagnostics that may highlight what is causing this issue, though? I'd really love to use LBM, but I prefer a smooth mouse over LBM functionality...

**Comment by COWCATGames** [comment]
I also get the stuttering issue. It happens once in a while, especially after a Windows hibernate restore but sometimes it won't stop at all. The mouse pointer is unusable when this happens.
Overall LBM is very buggy for me. Opening the control panel takes ages, sometimes won't open at all, and applying changes will work sometimes but not always. Today I got a new monitor to replace a faulty one and I just couldn't open the control panel. I had to revert to an older version and after insisting, it finally worked... For now at least.

**Comment by Kiefy** [comment]
Every time my system boots into windows and starts LBM, my mouse becomes unusably laggy for about 30 seconds.  I've just learned to accept it.

**Comment by carpetdev** [comment]
> Every time my system boots into windows and starts LBM, my mouse becomes unusably laggy for about 30 seconds. I've just learned to accept it.

Took me two years to realise that it was LBM causing this issue (it happens on wake for me - I think I'm using S3 sleep). For me, the lag sometimes disappears but more often I need to restart as it returns after a minute or two. Rarely, I need to restart once more which is extra frustrating.

Overall, I don't think this issue is fixed. I'll provide some more diagnostics and attempt to debug soon.

**Comment by TheZitroX** [comment]
Same thing for me. At startup or randomly after some time it lags the cursor for 5s @ 1fps.
I will disable LBM for a few days and when the lag never happens again it's caused by LBM and should be fixed.

**Comment by COWCATGames** [comment]
Although the latest updates made it a bit more responsive, I still get lags and very often LBM crashes out after hibernate. And when I start it back, often it will "skip" a monitor (the mouse pointer stays on the other monitors) until I manually shut down the monitor.

It doesn't like hibernate much...but I love hibernate mode personally...
