### ISSUE TITLE
Mouse Cursor gets stuck in small window after computer wakes up from sleep mode

### ISSUE THREAD

**Issue by EPICX09** [mgth/LittleBigMouse#303]
I have 2 monitors I use little big mouse with (Monitor 1 2560x1440) (And monitor 2 1920x1080) and whenever my PC wakes up from sleep, the mouse cursor only allows it to be in 1920x1080 of the 2560x1440 screen.

https://github.com/mgth/LittleBigMouse/assets/40742194/4cda4962-1145-4086-87bf-4d1b44f05e1b

**Comment by ww123td** [comment]
I am having the same issue. If I try to open the LBM GUI, the main display would be missing.

**Comment by Littledaimon** [comment]
Getting this issue every time my monitors go to sleep. I believe it is related to the fact the monitors stop being recognized by the system when they are asleep.
version 5.1.0.0

**Comment by ww123td** [comment]
> I am having the same issue. If I try to open the LBM GUI, the main display would be missing.

Update: it turned out to be an issue with Windows. Solved by uninstalling all of the unused monitors in Device Manager as well as trying the registry fixes posted [here on Superuser.com](https://superuser.com/questions/453446/how-can-i-stop-windows-re-positioning-after-waking-from-sleep).

**Comment by Littledaimon** [comment]
> > I am having the same issue. If I try to open the LBM GUI, the main display would be missing.
> 
> Update: it turned out to be an issue with Windows. Solved by uninstalling all of the unused monitors in Device Manager as well as trying the registry fixes posted [here on Superuser.com](https://superuser.com/questions/453446/how-can-i-stop-windows-re-positioning-after-waking-from-sleep).

Tried the fix proposed by ww123td but it did not solve the problem

Deleting registry keys
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Configuration 
and 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\GraphicsDrivers\Connectivity

Now different things happen with LBM:
1. sometimes still locks me into a corner of one screen
2. sometimes works properly
3. sometimes stops working (green start arrow becomes avaliable in the UI)

**Comment by mgth** [comment]
👋 **[LittleBigMouse 5.4.0](https://github.com/mgth/LittleBigMouse/releases/tag/v5.4.0) is out and should fix this.**

After wake the engine could keep running against a stale monitor layout (the burst of display-change events Windows sends on resume raced the engine), which can confine the cursor to a wrong region — like the 1920x1080 box you recorded on your 1440p screen. 5.4.0 re-hooks the engine on resume and adds a watchdog that checks it is actually running afterwards.

Note that 5.4.0 requires the [.NET 10 Desktop Runtime (x64)](https://dotnet.microsoft.com/en-us/download/dotnet/10.0). Please give it a try and post back either way.
