### ISSUE TITLE
size not saved

### ISSUE THREAD

**Issue by dmarois** [mgth/LittleBigMouse#34]
If I change the size of a screen and save, it is not applied.
if I exit and reload, the original size is back.
I dont seem to find a way to see my changes.

however, looking at the registry, I see that they are commited. but not loaded back in the application

changing location works. moving screens around and saving (and exiting and restarting the application) I can see the changes.
But I need to exit and restart. they are not applied "live" or by doing a stop/start

Thanks !

**Comment by mgth** [comment]
ok, the notification thing was broken. I think it's fixed now.

**Comment by dmarois** [comment]
I installed beta 4 and I still have the same issue saving resize information.
if I resize a screen, click apply/save and close the app config screen and reopen it.
all resize are lost and the screens are back at their default size.
however, I do see the changes in the registry.

prior of installing Beta4, I made sure I uninstalled the old version and I also wiped the registry for mgth
Thanks !
